### ISSUE TITLE
BC issues 

### ISSUE THREAD

**Issue by Milky063** [BigWigsMods/BigWigs_BurningCrusade#14]
1x BigWigs_BurningCrusade\Karazhan\Nightbane.lua:57: bad argument #1 to 'format' (string expected, got nil)
[C]: in function `format'
BigWigs_BurningCrusade\Karazhan\Nightbane.lua:57: in function `OnEngage'
BigWigs_Core\BossPrototype.lua:862: in function `?'
BigWigs_Core\BossPrototype.lua:405: in function `?'
BigWigs_Core\Core.lua:59: in function <BigWigs_Core\Core.lua:54>

Locals:
Skipped (In Encounter)

Getting this error on this fight, my addon BugSack picked it up.

**Comment by funkydude** [comment]
Will be resolved in the next release, thanks!
