### ISSUE TITLE
romulo and julianne  3 errors

### ISSUE THREAD

**Issue by milotic** [BigWigsMods/BigWigs_BurningCrusade#18]
BigWigs_BurningCrusade-v8.0.2-9-g0104536.zip

![WoWScrnShot_110820_000631](https://user-images.githubusercontent.com/1099848/98458452-79d77700-2156-11eb-9ae6-2eb24b74cde8.jpg)
![WoWScrnShot_110820_000632](https://user-images.githubusercontent.com/1099848/98458453-79d77700-2156-11eb-9094-92d03cbf4fc3.jpg)

**Comment by funkydude** [comment]
Please do not use alpha releases unless you are willing to experience these issues. And when you do, do not spam open multiple issues. Thank you.

**Comment by funkydude** [comment]
A new alpha of BigWigs_BurningCrusade is now available to be compatible with the alpha versions of BigWigs. Thank you.
