### ISSUE TITLE
Are you interested in nit picky timer issues ?

### ISSUE THREAD

**Issue by Jaladhjin** [BigWigsMods/BigWigs_BurningCrusade#9]
Not to seem unkind or ungrateful ;-)

Just figured I'd mention slight timing issues as I encounter them since I do old clears every week :-D

Or are you not really interested in especially old raid specifics ?

**Comment by nebularg** [comment]
Feel free to create a pull request with any fixes you have

**Comment by Jaladhjin** [comment]
I'm not a coder but I suspect a timer is probably the easiest thing there is..

Is there a format or something I can just paste like 10 seconds 12 seconds 40 seconds into or something ?
